* Bootstrapping postit.kaihola.fi
I have GitHub repos set up for the posts in my blog/wiki ("postit")
and the publishing engine ("sanapano").

I'm writing the posts in Emacs org-mode and the publishing engine in
Python WSGI.  The engine will render posts into static pages.  I've
set up a post-receive hook on GitHub for notifying the engine and
publishing changes all the way into postit.kaihola.fi.

One of the first things to decide is how to mark up metadata in
org-mode.  I'd like to have a shortcut for marking a post "published"
or "updated" and have a timestamp set automatically.  A good way might
be to create and use custom TODO states.

The publishing engine should go through all .org files in the "postit"
repository, parse them and convert each published top-level item into
an HTML file.

Oh, and before you ask, I am aware of existing tools for this kind of
workflow.  I guess I'm just suffering from the NIH syndrome, but I
also want the tools to adapt to my existing habits and not vice versa.

The next step now is to make a minimal version of the publishing
engine to get this post on-line.  Off to coding now.
* Design of my publishing engine
I'm building up from scratch with a minimal Python WSGI skeleton.  I
decided to take this approach and add dependencies as needed instead
of deciding on a web framework from the start.
